/** Clinical context and literature for GP-facing PDF exports. */

export interface ClinicalReference {
  id: string;
  citation: string;
  relevance: string;
}

export const CLINICAL_REFERENCES: ClinicalReference[] = [
  {
    id: 'voice-acoustic',
    citation:
      'Roy N, Barkmeier-Kraemer J, Eadie T, et al. (2013). Evidence-based clinical voice assessment. Journal of Medical Speech-Language Pathology.',
    relevance:
      'Jitter, shimmer, HNR, and maximum phonation time are established acoustic voice measures used in UK speech and language therapy assessment.',
  },
  {
    id: 'praat',
    citation:
      'Boersma P, Weenink D. Praat: doing phonetics by computer (software). University of Amsterdam.',
    relevance:
      'Baseline voice metrics use Praat-equivalent algorithms (praatfan) for local jitter (%), shimmer (%), and HNR (dB).',
  },
  {
    id: 'voice-norms',
    citation:
      'Fisher KV, Heman-Ackah YD, Finnegan E, et al. (2001). Vocal stability in normal speakers. Journal of Voice.',
    relevance:
      'Normative jitter and shimmer ranges inform the Stable / Monitor / Discuss thresholds in this report.',
  },
  {
    id: 'reaction-time',
    citation:
      'Deary IJ, Liewald D, Nissan J. (2011). Reaction time and intelligence differences: a population-based cohort study. Psychological Science.',
    relevance:
      'Simple and choice reaction time reflect processing speed and attention — useful for longitudinal self-monitoring, not diagnosis.',
  },
  {
    id: 'cognitive-motor',
    citation:
      'Salthouse TA. (2010). Selective review of cognitive aging. Journal of the International Neuropsychological Society.',
    relevance:
      'Motor and cognitive reaction tasks can show gradual change over time; single sessions should not be interpreted in isolation.',
  },
  {
    id: 'rppg',
    citation:
      'Verkruysse W, Svaasand LO, Nelson JS. (2008). Remote plethysmographic imaging using ambient light. Optics Express.',
    relevance:
      'Camera-based heart rate (rPPG) estimates pulse from facial skin colour changes; accuracy depends on lighting and stillness.',
  },
  {
    id: 'blink',
    citation:
      'Bentivoglio AR, Bressman SB, Cassetta E, et al. (1997). Analysis of blink rate in healthy subjects. Neurology.',
    relevance:
      'Normal adult blink rate is typically 15–20 blinks per minute; deviation may reflect fatigue, medication, or ocular conditions.',
  },
];

export const VOICE_THRESHOLDS = {
  jitter: { stable: '< 0.5%', monitor: '0.5–2.0%', flag: '> 2.0%' },
  shimmer: { stable: '< 5%', monitor: '5–12%', flag: '> 12%' },
  hnr: { stable: '> 20 dB', monitor: '12–20 dB', flag: '< 12 dB' },
  mpt: { stable: '≥ 18 s', monitor: '10–18 s', flag: '< 10 s' },
} as const;

export const REACTION_THRESHOLDS = {
  tapMs: { stable: '< 350 ms', monitor: '350–500 ms', flag: '> 500 ms' },
  choiceMs: { stable: '< 450 ms', monitor: '450–650 ms', flag: '> 650 ms' },
  choiceAccuracy: { stable: '≥ 90%', monitor: '75–89%', flag: '< 75%' },
} as const;

export const HEART_RATE_THRESHOLDS = {
  resting: { stable: '60–100 bpm', monitor: '50–59 or 101–110 bpm', flag: '< 50 or > 110 bpm' },
} as const;

export const REPORT_DISCLAIMER =
  'This report is generated by Baseline, a self-administered home monitoring tool. ' +
  'Results are for trend review at routine appointments only — not a diagnostic instrument. ' +
  'Interpret alongside clinical history, examination, and validated investigations.';
